version: '3.8'

services:
  php-mongodb-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker_php_mongodb
    ports:
      - "8080:80"  # Expose le port 8080 de votre machine hôte vers le port 80 du conteneur
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mongo

  mongo:
    container_name: docker_mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
